version: '3'
services: 
   node-web-app:
    build: .
    ports:
      - ":3000:8080"
    networks:
        my-network:
          aliases:
          - node-container1
    healthcheck:
      test: curl --fail /Hello from Mumu || exit 1
      interval: 60s
      timeout: 60s
      retries: 3
   another-container2:
    image: node-web-app2
    command: sh -c "echo 'Hello from container2' && server.js"
    expose:
        - "3000"
    networks: 
          my-network:
            aliases:
              - container2
    healthcheck:
      test: curl --fail /Hello from Mumu || exit 1
      interval: 60s
      timeout: 60s
      retries: 3
networks:
  my-network:
    driver: bridge




     